### ISSUE TITLE
v0.3.12 fails on pnpm dev

### ISSUE THREAD

**Issue by rkmitra1** [redwoodjs/sdk#789]
"rwsdk": "0.3.12" fails simple create and startup
works with  "rwsdk": "0.2.0-alpha.15",

Steps to recreate:
1. npx create-rwsdk rwsdk-test -t minimal
2. cd rwsdk-test
3. pnpm install
4. pnpm dev
5. errors

pnpm dev

> @redwoodjs/starter-minimal@1.0.0 dev /Users/user1/Documents/mytest/Files/RedwoodSDK/rwsdk-test
> vite dev

error when starting dev server:
TypeError: Promise.withResolvers is not a function
    at directiveModulesDevPlugin (file:///Users/user1/Documents/mytest/Files/RedwoodSDK/rwsdk-test/node_modules/.pnpm/rwsdk@0.3.12_rollup@4.52.2_typescript@5.9.2_vite@6.3.6_@types+node@22.18.6_terser@5.44._7c5e324f7ed578e7b41a67a431e6eda7/node_modules/rwsdk/dist/vite/directiveModulesDevPlugin.mjs:34:75)

**Comment by rkmitra1** [comment]
Node version problems. updated to node v22.20.0 and all works.
